package Integracion;

import javax.swing.JOptionPane;
import org.nfunk.jep.ParseException;

/**
 *
 * @author jam
 */
public class EDO extends javax.swing.JFrame {

  private double[] f;
  private Funcion fun;
  public EDO() {
    initComponents();
    setLocationRelativeTo(null);
    metodo.removeAllItems();
    metodo.addItem("Método de Euler");
    metodo.addItem("Método de Taylor");
    metodo.addItem("Método de Runge-Kutta");
    fx.requestFocus();
  }
  
public String euler(int a, double h) throws ParseException{
  String re="";
  for (int i = 0; i < f.length-1; i++) {
    double x = a + (i*h);
    f[i+1] = fun.Redondear(f[i] + h*(fun.Evaluar(x, f[i])));
    re += (String.format("Iteración # %d:\nX = %.4f\nW = %.4f", i, x, f[i]));
    if (i < f.length-2) {
      re +="\n\n";
    }
  }
  return re;
}


public int fact(int n){
  int ret=1;
  for (int i = 2; i <= n; i++)
    ret *= n;
  return ret;
}


public String reemplazar(String ori, String cambio, String reem){
  while(ori.indexOf(cambio) != -1){
    ori = ori.replace(cambio, reem);
  }
  return ori;
}


public String t(int n, double h){
  String ret="";
  String der = fun.getF();
  for (int i = 0; i < n; i++) {
    if(i != 0){
      String der1 = JOptionPane.showInputDialog(null, "Ingrese la derivada de "+der+":",der);
      der = reemplazar(der1, "'diff(y,x,1)", fun.getF());
    }
    if(i != n-1)
      ret += String.format("(%.4f)(%s) + ", (i!=0 ? fun.Redondear(h/fact(i+1)) : 1.0), der);
    else
      ret += String.format("(%.4f)(%s)", (i!=0 ? fun.Redondear(h/fact(i+1)) : 1.0), der);
  }
  return ret;
}


public String taylor(int a, double h, int n) throws ParseException{
  String re="";
  String t = t(n,h);
  fun.setF(t);
  for (int i = 0; i < f.length-1; i++) {
    if(i!=0){
      double x = a + ((i-1)*h);
      double xi = a + (i*h);
      f[i] = fun.Redondear(f[i-1] + h*fun.Evaluar(x, f[i-1]));
      re += String.format("Iteración # %d:\nX = %.4f\nW = %.4f", i,xi,f[i]);
    }else
      re += String.format("Iteración # 0:\nX = %d\nW = %.4f", a, f[i]);
    if (i < f.length-2) {
      re +="\n\n";
    }
  }
  return re;
}


public String runge(int a, double h) throws ParseException{
  String re="";
  for (int i = 0; i < f.length-1; i++) {
    if(i!=0){
      double x = a + ((i-1)*h);
      double xi = a + (i*h);
      double k1=fun.Redondear(h*fun.Evaluar(x, f[i-1]));
      double k2=fun.Redondear(h*fun.Evaluar((x+(h/2)), f[i-1]+(k1/2)));
      double k3=fun.Redondear(h*fun.Evaluar(x+(h/2), f[i-1]+(k2/2)));
      double k4=fun.Redondear(h*fun.Evaluar(xi, f[i-1]+k3));
      f[i] = fun.Redondear(f[i-1] + (k1+(2*k2)+(2*k3)+k4)/6);
      re += String.format("Iteración # %d:\nK1 = %.4f\nK2 = %.4f\nK3 = %.4f\nK4 = %.4f\nX = %.4f\nW = %.4f", i,k1,k2,k3,k4,xi,f[i]);
    }else
      re += String.format("Iteración # 0:\nK1 = ---\nK2 = ---\nK3 = ---\nK4 = ---\nX = %d\nW = %.4f", a, f[i]);
    if (i < f.length-2) {
      re +="\n\n";
    }
  }
  return re;
}

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        metodo = new javax.swing.JComboBox();
        B = new javax.swing.JSpinner();
        limpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        A = new javax.swing.JSpinner();
        fx = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        res = new javax.swing.JTextArea();
        salir = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();
        n = new javax.swing.JSpinner();
        lblin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        condicion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        aceptar1 = new javax.swing.JButton();

        jButton1.setText("Informacion");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        metodo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        metodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                metodoItemStateChanged(evt);
            }
        });
        metodo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                metodoFocusLost(evt);
            }
        });
        metodo.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                metodoCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        metodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metodoActionPerformed(evt);
            }
        });
        metodo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                metodoPropertyChange(evt);
            }
        });
        metodo.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                metodoVetoableChange(evt);
            }
        });
        getContentPane().add(metodo);
        metodo.setBounds(158, 58, 331, 22);

        B.setNextFocusableComponent(n);
        getContentPane().add(B);
        B.setBounds(372, 233, 59, 22);

        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Integracion/boton-actualizar.png"))); // NOI18N
        limpiar.setToolTipText("Limpiar");
        limpiar.setNextFocusableComponent(salir);
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(limpiar);
        limpiar.setBounds(10, 460, 190, 40);

        jLabel4.setText("≤ x ≤");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 236, 32, 16);

        A.setNextFocusableComponent(B);
        getContentPane().add(A);
        A.setBounds(167, 233, 63, 22);

        fx.setNextFocusableComponent(A);
        fx.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fxFocusGained(evt);
            }
        });
        getContentPane().add(fx);
        fx.setBounds(293, 123, 196, 22);

        jScrollPane1.setEnabled(false);

        res.setEditable(false);
        res.setColumns(20);
        res.setFont(new java.awt.Font("Ubuntu", 0, 26)); // NOI18N
        res.setRows(5);
        res.setFocusable(false);
        jScrollPane1.setViewportView(res);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(209, 337, 532, 340);

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Integracion/Imagen2.png"))); // NOI18N
        salir.setToolTipText("Salir");
        salir.setBorderPainted(false);
        salir.setNextFocusableComponent(fx);
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        getContentPane().add(salir);
        salir.setBounds(0, 510, 200, 80);

        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Integracion/boton-calcular.png"))); // NOI18N
        aceptar.setToolTipText("Aceptar");
        aceptar.setNextFocusableComponent(limpiar);
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar);
        aceptar.setBounds(10, 370, 130, 60);

        n.setNextFocusableComponent(condicion);
        getContentPane().add(n);
        n.setBounds(220, 310, 84, 22);

        lblin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblin.setForeground(new java.awt.Color(255, 255, 51));
        lblin.setText("N");
        getContentPane().add(lblin);
        lblin.setBounds(200, 300, 50, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Y(a)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 310, 40, 20);

        condicion.setNextFocusableComponent(aceptar);
        getContentPane().add(condicion);
        condicion.setBounds(400, 310, 59, 22);

        jLabel3.setBackground(new java.awt.Color(51, 51, 0));
        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Ecuaciones diferenciales Ordinairas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 10, 269, 29);

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Funcion a Integrar:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(143, 113, 140, 29);

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Hasta:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(372, 202, 46, 29);

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Establecer los limites:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 160, 164, 29);

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Desde:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(167, 200, 50, 29);

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setText("Establecer Numeros de Iteraciones:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(214, 271, 268, 29);

        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Integracion/frase-einstein-problemas.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-210, 0, 980, 760);

        jLabel10.setBackground(new java.awt.Color(51, 51, 0));
        jLabel10.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Ecuaciones diferenciales Ordinairas");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(201, 11, 269, 29);

        jLabel11.setBackground(new java.awt.Color(51, 51, 0));
        jLabel11.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText("Ecuaciones diferenciales Ordinairas");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(201, 11, 269, 29);

        aceptar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Integracion/boton-calcular.png"))); // NOI18N
        aceptar1.setToolTipText("Aceptar");
        aceptar1.setNextFocusableComponent(limpiar);
        aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptar1ActionPerformed(evt);
            }
        });
        getContentPane().add(aceptar1);
        aceptar1.setBounds(10, 370, 130, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void metodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_metodoItemStateChanged

  }//GEN-LAST:event_metodoItemStateChanged

  private void metodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metodoActionPerformed

 }//GEN-LAST:event_metodoActionPerformed

  private void metodoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_metodoFocusLost

 }//GEN-LAST:event_metodoFocusLost

  private void metodoCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_metodoCaretPositionChanged

 }//GEN-LAST:event_metodoCaretPositionChanged

  private void metodoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_metodoPropertyChange
    // TODO add your handling code here:
  }//GEN-LAST:event_metodoPropertyChange

  private void metodoVetoableChange(java.beans.PropertyChangeEvent evt) throws java.beans.PropertyVetoException {//GEN-FIRST:event_metodoVetoableChange

 }//GEN-LAST:event_metodoVetoableChange

  private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
    n.setValue(0);
    A.setValue(0);
    B.setValue(0);
    res.setText(null);
    fx.setText(null);
    fx.requestFocus();
  }//GEN-LAST:event_limpiarActionPerformed

  private void fxFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fxFocusGained

 }//GEN-LAST:event_fxFocusGained

  private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
    System.exit(0);
  }//GEN-LAST:event_salirActionPerformed

  private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
    f = new double[Integer.parseInt(n.getValue().toString()) + 2];
    double h = (Double.parseDouble(B.getValue().toString()) - Double.parseDouble(A.getValue().toString())) / Double.parseDouble(n.getValue().toString());
    fun = new Funcion(fx.getText());
    String msg = "";
    int a = Integer.parseInt(A.getValue().toString());
    f[0] = Double.parseDouble(condicion.getText().toString());
    String re="";
    boolean correcto = true;
    
    switch(metodo.getSelectedIndex()){
      case 0:
        try {
          re = euler(a, h);
        } catch (ParseException ex) {
          msg = "Función Incorrecta";
          correcto = false;
        }
        break;
        
      case 1:
        try {
          int nu = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese el Orden", 2));
          re = taylor(a, h, nu);
        } catch (ParseException ex) {
          msg = "Función Incorrecta";
          correcto = false;
        }
        break;
        
      case 2:
        try {
          re = runge(a,h);
        } catch (ParseException ex) {
          msg = "Función Incorrecta";
          correcto = false;
        }
        break;
    }
    if(correcto)
      res.setText(re);
    else
      JOptionPane.showMessageDialog(null, msg, "Error", 0);
    fx.requestFocus();
  }//GEN-LAST:event_aceptarActionPerformed

    private void aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptar1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /*
     * Set the Nimbus look and feel
     */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
     * If Nimbus (introduced in Java SE 6) is not available, stay with the
     * default look and feel. For details see
     * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(EDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(EDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(EDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(EDO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /*
     * Create and display the form
     */
    java.awt.EventQueue.invokeLater(new Runnable() {

      public void run() {
        new EDO().setVisible(true);
      }
    });
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner A;
    private javax.swing.JSpinner B;
    private javax.swing.JButton aceptar;
    private javax.swing.JButton aceptar1;
    private javax.swing.JTextField condicion;
    private javax.swing.JTextField fx;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblin;
    private javax.swing.JButton limpiar;
    private javax.swing.JComboBox metodo;
    private javax.swing.JSpinner n;
    private javax.swing.JTextArea res;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
